[tasks.wasm-pack-dev]
command = "bash"
args = ["pack-local.sh"]
watch = true

[tasks.webpack]
command = "npm"
args = ["run", "build", "--", "--mode=production"]

[tasks.run-dev]
command = "cargo"
args = ["run"]
watch = true

[tasks.build]
dependencies = ["webpack"]
command = "cargo"
args = ["build", "--release"]
