[tasks.wasm-pack-dev]
command = "wasm-pack"
args = ["build", "--target", "web", "--dev"]
watch = true

[tasks.wasm-pack]
command = "wasm-pack"
args = ["build", "--target", "web"]

[tasks.webpack-dev]
command = "webpack"
watch = true

[tasks.webpack]
command = "webpack"
args = ["--mode=production"]

[tasks.run-dev]
command = "cargo"
args = ["run"]
watch = true

[tasks.build]
dependencies = ["webpack"]
command = "cargo"
args = ["build", "--release"]
